apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s

  - name: PostgreSQL
    type: postgres
    access: proxy
    orgId: 1
    url: postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/orlahs
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      sslmode: disable
      maxOpenConnections: 0
      maxIdleConnections: 2
      maxConnectionLifetime: 14400